### ISSUE TITLE
angular tour directive not  getting initialized.

### ISSUE THREAD

**Issue by Ankita-Palekar** [DaftMonk/angular-tour#50] opened 2015-09-28 09:44 UTC
Here is the plunker link what I am trying for http://embed.plnkr.co/TRD9tI5Vh1PYZSlVYvoZ/script.js
angular-tour directive is not initializing and it does not show any popover neither does it show any errors console.

**Comment by mtparsons** [comment] 2015-10-02 16:17
+1 Experiencing the same issue! I think the issue is in the packaging behavior.  

When I changed the files in dist locally I removed:
https://github.com/DaftMonk/angular-tour/blob/master/dist/angular-tour-tpls.js#L13

and just used:
https://github.com/DaftMonk/angular-tour/blob/master/dist/angular-tour-tpls.js#L12

Here's when it starts popping up:
https://github.com/DaftMonk/angular-tour/commit/ceeeac02fedcaa3b368ca0092c3298918ed6fd5d

Haven't dived into the Gruntfile but I don't see any recent changes there

**Comment by booleanbetrayal** [comment] 2015-10-02 19:38
I have no idea how that happened ... I stamped another build though that doesn't exhibit the odd packaging bug. Please let me know if you're having any other issues. Closing but can re-open.

ec9e943359bb409a47dabbd16f9e3cd8c3a15ab0

**Closed by booleanbetrayal** 2015-10-02 19:38 UTC

**Comment by mtparsons** [comment] 2015-10-05 21:26
Thanks for taking care of it so quickly either way!
